name: Monitor de Precios Lauro
on:
  schedule:
    - cron: '0 13 * * *' 
  workflow_dispatch:

jobs:
  track-prices:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar librerías necesarias
        run: pip install requests beautifulsoup4  # <--- ESTO ES LO QUE FALTABA

      - name: Ejecutar el script de monitoreo
        run: python monitor.py

      - name: Guardar cambios en el Excel
        run: |
          git config --global user.name 'PC-Price-Bot'
          git config --global user.email 'bot@github.com'
          git add presupuesto_pc_lauro.csv
          git commit -m "Update precios build $(date +'%d/%m/%Y')" || exit 0
          git push
